/home/airflow/.local/lib/python3.8/site-packages/airflow/configuration.py:816 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
/home/airflow/.local/lib/python3.8/site-packages/airflow/configuration.py:742 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
/home/airflow/.local/lib/python3.8/site-packages/airflow/models/base.py:71 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py:224 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[[34m2025-09-20T05:03:38.199+0000[0m] {[34mexecutor_loader.py:[0m117} INFO[0m - Loaded executor: LocalExecutor[0m
[2025-09-20 05:03:38 +0000] [34] [INFO] Starting gunicorn 21.2.0
[2025-09-20 05:03:38 +0000] [34] [INFO] Listening at: http://[::]:8793 (34)
[2025-09-20 05:03:38 +0000] [34] [INFO] Using worker: sync
[[34m2025-09-20T05:03:38.655+0000[0m] {[34mscheduler_job_runner.py:[0m797} INFO[0m - Starting the scheduler[0m
[[34m2025-09-20T05:03:38.804+0000[0m] {[34mscheduler_job_runner.py:[0m804} INFO[0m - Processing each file at most -1 times[0m
[2025-09-20 05:03:38 +0000] [35] [INFO] Booting worker with pid: 35
[2025-09-20 05:03:38 +0000] [36] [INFO] Booting worker with pid: 36
[[34m2025-09-20T05:03:41.216+0000[0m] {[34mmanager.py:[0m166} INFO[0m - Launched DagFileProcessorManager with pid: 165[0m
[[34m2025-09-20T05:03:41.236+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T05:03:41.437+0000[0m] {[34msettings.py:[0m61} INFO[0m - Configured default timezone Timezone('UTC')[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-20T05:03:41.811+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 4 SchedulerJob instances as failed[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py:407 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-20T05:08:42.279+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T05:13:42.384+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T05:18:42.549+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T05:23:42.677+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T05:23:57.788+0000[0m] {[34mscheduler_job_runner.py:[0m413} INFO[0m - 1 tasks up for execution:
	<TaskInstance: silver_to_gold.process_silver_to_gold manual__2025-09-20T03:29:08+00:00 [scheduled]>[0m
[[34m2025-09-20T05:23:57.789+0000[0m] {[34mscheduler_job_runner.py:[0m476} INFO[0m - DAG silver_to_gold has 0/16 running and queued tasks[0m
[[34m2025-09-20T05:23:57.791+0000[0m] {[34mscheduler_job_runner.py:[0m592} INFO[0m - Setting the following tasks to queued state:
	<TaskInstance: silver_to_gold.process_silver_to_gold manual__2025-09-20T03:29:08+00:00 [scheduled]>[0m
[[34m2025-09-20T05:23:57.797+0000[0m] {[34mtaskinstance.py:[0m1441} WARNING[0m - cannot record scheduled_duration for task process_silver_to_gold because previous state change time has not been saved[0m
[[34m2025-09-20T05:23:57.807+0000[0m] {[34mscheduler_job_runner.py:[0m635} INFO[0m - Sending TaskInstanceKey(dag_id='silver_to_gold', task_id='process_silver_to_gold', run_id='manual__2025-09-20T03:29:08+00:00', try_number=1, map_index=-1) to executor with priority 1 and queue default[0m
[[34m2025-09-20T05:23:57.808+0000[0m] {[34mbase_executor.py:[0m146} INFO[0m - Adding to queue: ['airflow', 'tasks', 'run', 'silver_to_gold', 'process_silver_to_gold', 'manual__2025-09-20T03:29:08+00:00', '--local', '--subdir', 'DAGS_FOLDER/pipeline_silver_to_gold.py'][0m
[[34m2025-09-20T05:23:57.925+0000[0m] {[34mlocal_executor.py:[0m89} INFO[0m - QueuedLocalWorker running ['airflow', 'tasks', 'run', 'silver_to_gold', 'process_silver_to_gold', 'manual__2025-09-20T03:29:08+00:00', '--local', '--subdir', 'DAGS_FOLDER/pipeline_silver_to_gold.py'][0m
[[34m2025-09-20T05:23:58.461+0000[0m] {[34mdagbag.py:[0m536} INFO[0m - Filling up the DagBag from /opt/***/dags/pipeline_silver_to_gold.py[0m
[[34m2025-09-20T05:24:02.575+0000[0m] {[34mscheduler_job_runner.py:[0m413} INFO[0m - 1 tasks up for execution:
	<TaskInstance: silver_to_gold.process_silver_to_gold manual__2025-09-20T05:24:01.228677+00:00 [scheduled]>[0m
[[34m2025-09-20T05:24:02.582+0000[0m] {[34mscheduler_job_runner.py:[0m476} INFO[0m - DAG silver_to_gold has 1/16 running and queued tasks[0m
[[34m2025-09-20T05:24:02.588+0000[0m] {[34mscheduler_job_runner.py:[0m592} INFO[0m - Setting the following tasks to queued state:
	<TaskInstance: silver_to_gold.process_silver_to_gold manual__2025-09-20T05:24:01.228677+00:00 [scheduled]>[0m
[[34m2025-09-20T05:24:02.601+0000[0m] {[34mtaskinstance.py:[0m1441} WARNING[0m - cannot record scheduled_duration for task process_silver_to_gold because previous state change time has not been saved[0m
[[34m2025-09-20T05:24:02.602+0000[0m] {[34mscheduler_job_runner.py:[0m635} INFO[0m - Sending TaskInstanceKey(dag_id='silver_to_gold', task_id='process_silver_to_gold', run_id='manual__2025-09-20T05:24:01.228677+00:00', try_number=1, map_index=-1) to executor with priority 1 and queue default[0m
[[34m2025-09-20T05:24:02.604+0000[0m] {[34mbase_executor.py:[0m146} INFO[0m - Adding to queue: ['airflow', 'tasks', 'run', 'silver_to_gold', 'process_silver_to_gold', 'manual__2025-09-20T05:24:01.228677+00:00', '--local', '--subdir', 'DAGS_FOLDER/pipeline_silver_to_gold.py'][0m
[[34m2025-09-20T05:24:02.650+0000[0m] {[34mlocal_executor.py:[0m89} INFO[0m - QueuedLocalWorker running ['airflow', 'tasks', 'run', 'silver_to_gold', 'process_silver_to_gold', 'manual__2025-09-20T05:24:01.228677+00:00', '--local', '--subdir', 'DAGS_FOLDER/pipeline_silver_to_gold.py'][0m
[[34m2025-09-20T05:24:02.873+0000[0m] {[34mdagbag.py:[0m536} INFO[0m - Filling up the DagBag from /opt/***/dags/pipeline_silver_to_gold.py[0m
Changing /opt/airflow/logs/dag_id=silver_to_gold/run_id=manual__2025-09-20T03:29:08+00:00/task_id=process_silver_to_gold permission to 509
[[34m2025-09-20T05:24:02.898+0000[0m] {[34mtask_command.py:[0m416} INFO[0m - Running <TaskInstance: silver_to_gold.process_silver_to_gold manual__2025-09-20T03:29:08+00:00 [queued]> on host 2b8018637437[0m
Changing /opt/airflow/logs/dag_id=silver_to_gold/run_id=manual__2025-09-20T05:24:01.228677+00:00/task_id=process_silver_to_gold permission to 509
[[34m2025-09-20T05:24:06.894+0000[0m] {[34mtask_command.py:[0m416} INFO[0m - Running <TaskInstance: silver_to_gold.process_silver_to_gold manual__2025-09-20T05:24:01.228677+00:00 [queued]> on host 2b8018637437[0m
[[34m2025-09-20T05:24:09.356+0000[0m] {[34mdagrun.py:[0m632} ERROR[0m - Marking run <DagRun silver_to_gold @ 2025-09-20 03:29:08+00:00: manual__2025-09-20T03:29:08+00:00, state:running, queued_at: 2025-09-20 03:29:08.748378+00:00. externally triggered: True> failed[0m
[[34m2025-09-20T05:24:09.363+0000[0m] {[34mdagrun.py:[0m704} INFO[0m - DagRun Finished: dag_id=silver_to_gold, execution_date=2025-09-20 03:29:08+00:00, run_id=manual__2025-09-20T03:29:08+00:00, run_start_date=2025-09-20 05:23:57.633048+00:00, run_end_date=2025-09-20 05:24:09.363566+00:00, run_duration=11.730518, state=failed, external_trigger=True, run_type=manual, data_interval_start=2025-09-20 03:29:08+00:00, data_interval_end=2025-09-20 03:29:08+00:00, dag_hash=63062963df6b6808a3a782950bfe742c[0m
[[34m2025-09-20T05:24:11.112+0000[0m] {[34mscheduler_job_runner.py:[0m685} INFO[0m - Received executor event with state success for task instance TaskInstanceKey(dag_id='silver_to_gold', task_id='process_silver_to_gold', run_id='manual__2025-09-20T03:29:08+00:00', try_number=1, map_index=-1)[0m
[[34m2025-09-20T05:24:11.226+0000[0m] {[34mscheduler_job_runner.py:[0m722} INFO[0m - TaskInstance Finished: dag_id=silver_to_gold, task_id=process_silver_to_gold, run_id=manual__2025-09-20T03:29:08+00:00, map_index=-1, run_start_date=2025-09-20 05:24:04.888756+00:00, run_end_date=2025-09-20 05:24:09.179818+00:00, run_duration=4.291062, state=failed, executor_state=success, try_number=1, max_tries=0, job_id=20, pool=default_pool, queue=default, priority_weight=1, operator=PythonOperator, queued_dttm=2025-09-20 05:23:57.793515+00:00, queued_by_job_id=19, pid=630[0m
[[34m2025-09-20T05:24:13.063+0000[0m] {[34mdagrun.py:[0m632} ERROR[0m - Marking run <DagRun silver_to_gold @ 2025-09-20 05:24:01.228677+00:00: manual__2025-09-20T05:24:01.228677+00:00, state:running, queued_at: 2025-09-20 05:24:01.868773+00:00. externally triggered: True> failed[0m
[[34m2025-09-20T05:24:13.065+0000[0m] {[34mdagrun.py:[0m704} INFO[0m - DagRun Finished: dag_id=silver_to_gold, execution_date=2025-09-20 05:24:01.228677+00:00, run_id=manual__2025-09-20T05:24:01.228677+00:00, run_start_date=2025-09-20 05:24:02.378245+00:00, run_end_date=2025-09-20 05:24:13.065246+00:00, run_duration=10.687001, state=failed, external_trigger=True, run_type=manual, data_interval_start=2025-09-20 05:24:01.228677+00:00, data_interval_end=2025-09-20 05:24:01.228677+00:00, dag_hash=63062963df6b6808a3a782950bfe742c[0m
[[34m2025-09-20T05:24:13.111+0000[0m] {[34mscheduler_job_runner.py:[0m685} INFO[0m - Received executor event with state success for task instance TaskInstanceKey(dag_id='silver_to_gold', task_id='process_silver_to_gold', run_id='manual__2025-09-20T05:24:01.228677+00:00', try_number=1, map_index=-1)[0m
[[34m2025-09-20T05:24:13.125+0000[0m] {[34mscheduler_job_runner.py:[0m722} INFO[0m - TaskInstance Finished: dag_id=silver_to_gold, task_id=process_silver_to_gold, run_id=manual__2025-09-20T05:24:01.228677+00:00, map_index=-1, run_start_date=2025-09-20 05:24:09.953692+00:00, run_end_date=2025-09-20 05:24:11.376943+00:00, run_duration=1.423251, state=failed, executor_state=success, try_number=1, max_tries=0, job_id=21, pool=default_pool, queue=default, priority_weight=1, operator=PythonOperator, queued_dttm=2025-09-20 05:24:02.598789+00:00, queued_by_job_id=19, pid=631[0m
[[34m2025-09-20T05:24:45.033+0000[0m] {[34mscheduler_job_runner.py:[0m413} INFO[0m - 1 tasks up for execution:
	<TaskInstance: bronze_to_silver.process_bronze_to_silver manual__2025-09-20T05:24:43.703745+00:00 [scheduled]>[0m
[[34m2025-09-20T05:24:45.035+0000[0m] {[34mscheduler_job_runner.py:[0m476} INFO[0m - DAG bronze_to_silver has 0/16 running and queued tasks[0m
[[34m2025-09-20T05:24:45.036+0000[0m] {[34mscheduler_job_runner.py:[0m592} INFO[0m - Setting the following tasks to queued state:
	<TaskInstance: bronze_to_silver.process_bronze_to_silver manual__2025-09-20T05:24:43.703745+00:00 [scheduled]>[0m
[[34m2025-09-20T05:24:45.041+0000[0m] {[34mtaskinstance.py:[0m1441} WARNING[0m - cannot record scheduled_duration for task process_bronze_to_silver because previous state change time has not been saved[0m
[[34m2025-09-20T05:24:45.042+0000[0m] {[34mscheduler_job_runner.py:[0m635} INFO[0m - Sending TaskInstanceKey(dag_id='bronze_to_silver', task_id='process_bronze_to_silver', run_id='manual__2025-09-20T05:24:43.703745+00:00', try_number=1, map_index=-1) to executor with priority 1 and queue default[0m
[[34m2025-09-20T05:24:45.043+0000[0m] {[34mbase_executor.py:[0m146} INFO[0m - Adding to queue: ['airflow', 'tasks', 'run', 'bronze_to_silver', 'process_bronze_to_silver', 'manual__2025-09-20T05:24:43.703745+00:00', '--local', '--subdir', 'DAGS_FOLDER/pipeline_bronze_to_silver.py'][0m
[[34m2025-09-20T05:24:45.103+0000[0m] {[34mlocal_executor.py:[0m89} INFO[0m - QueuedLocalWorker running ['airflow', 'tasks', 'run', 'bronze_to_silver', 'process_bronze_to_silver', 'manual__2025-09-20T05:24:43.703745+00:00', '--local', '--subdir', 'DAGS_FOLDER/pipeline_bronze_to_silver.py'][0m
[[34m2025-09-20T05:24:45.310+0000[0m] {[34mdagbag.py:[0m536} INFO[0m - Filling up the DagBag from /opt/***/dags/pipeline_bronze_to_silver.py[0m
Changing /opt/airflow/logs/dag_id=bronze_to_silver/run_id=manual__2025-09-20T05:24:43.703745+00:00/task_id=process_bronze_to_silver permission to 509
[[34m2025-09-20T05:24:49.543+0000[0m] {[34mtask_command.py:[0m416} INFO[0m - Running <TaskInstance: bronze_to_silver.process_bronze_to_silver manual__2025-09-20T05:24:43.703745+00:00 [queued]> on host 2b8018637437[0m
[[34m2025-09-20T05:24:56.320+0000[0m] {[34mdagrun.py:[0m653} INFO[0m - Marking run <DagRun bronze_to_silver @ 2025-09-20 05:24:43.703745+00:00: manual__2025-09-20T05:24:43.703745+00:00, state:running, queued_at: 2025-09-20 05:24:43.837615+00:00. externally triggered: True> successful[0m
[[34m2025-09-20T05:24:56.322+0000[0m] {[34mdagrun.py:[0m704} INFO[0m - DagRun Finished: dag_id=bronze_to_silver, execution_date=2025-09-20 05:24:43.703745+00:00, run_id=manual__2025-09-20T05:24:43.703745+00:00, run_start_date=2025-09-20 05:24:44.990903+00:00, run_end_date=2025-09-20 05:24:56.322159+00:00, run_duration=11.331256, state=success, external_trigger=True, run_type=manual, data_interval_start=2025-09-20 05:24:43.703745+00:00, data_interval_end=2025-09-20 05:24:43.703745+00:00, dag_hash=df9b2f81b9ab8686c0e15a78077ee3b9[0m
[[34m2025-09-20T05:24:58.117+0000[0m] {[34mscheduler_job_runner.py:[0m685} INFO[0m - Received executor event with state success for task instance TaskInstanceKey(dag_id='bronze_to_silver', task_id='process_bronze_to_silver', run_id='manual__2025-09-20T05:24:43.703745+00:00', try_number=1, map_index=-1)[0m
[[34m2025-09-20T05:24:58.165+0000[0m] {[34mscheduler_job_runner.py:[0m722} INFO[0m - TaskInstance Finished: dag_id=bronze_to_silver, task_id=process_bronze_to_silver, run_id=manual__2025-09-20T05:24:43.703745+00:00, map_index=-1, run_start_date=2025-09-20 05:24:51.001604+00:00, run_end_date=2025-09-20 05:24:55.822840+00:00, run_duration=4.821236, state=success, executor_state=success, try_number=1, max_tries=0, job_id=22, pool=default_pool, queue=default, priority_weight=1, operator=PythonOperator, queued_dttm=2025-09-20 05:24:45.038697+00:00, queued_by_job_id=19, pid=646[0m
[[34m2025-09-20T05:28:42.793+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T05:33:42.970+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T05:38:43.128+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[2025-09-20 05:44:31 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:35)
[2025-09-20 05:44:32 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:36)
[2025-09-20 05:44:32 +0000] [36] [INFO] Worker exiting (pid: 36)
[2025-09-20 05:44:32 +0000] [35] [INFO] Worker exiting (pid: 35)
[2025-09-20 05:44:32 +0000] [34] [ERROR] Worker (pid:35) exited with code 1
[2025-09-20 05:44:32 +0000] [34] [ERROR] Worker (pid:35) exited with code 1.
[2025-09-20 05:44:32 +0000] [34] [ERROR] Worker (pid:36) exited with code 1
[2025-09-20 05:44:33 +0000] [34] [ERROR] Worker (pid:36) exited with code 1.
[2025-09-20 05:44:33 +0000] [1037] [INFO] Booting worker with pid: 1037
[2025-09-20 05:44:33 +0000] [1038] [INFO] Booting worker with pid: 1038
[[34m2025-09-20T05:44:41.577+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T05:49:41.495+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T05:54:41.559+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T05:59:41.639+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T06:04:41.719+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T06:09:41.785+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T06:14:41.883+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T06:19:41.972+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T06:24:42.146+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[2025-09-20 06:31:26 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:1037)
[2025-09-20 06:31:26 +0000] [1037] [INFO] Worker exiting (pid: 1037)
[2025-09-20 06:31:26 +0000] [34] [ERROR] Worker (pid:1037) exited with code 1
[[34m2025-09-20T06:31:26.593+0000[0m] {[34mmanager.py:[0m302} ERROR[0m - DagFileProcessorManager (PID=165) last sent a heartbeat 291.01 seconds ago! Restarting it[0m
[2025-09-20 06:31:26 +0000] [34] [ERROR] Worker (pid:1037) exited with code 1.
[2025-09-20 06:31:26 +0000] [1963] [INFO] Booting worker with pid: 1963
[[34m2025-09-20T06:31:26.537+0000[0m] {[34mprocess_utils.py:[0m131} INFO[0m - Sending Signals.SIGTERM to group 165. PIDs of all processes in the group: [165][0m
[[34m2025-09-20T06:31:26.549+0000[0m] {[34mprocess_utils.py:[0m86} INFO[0m - Sending the signal Signals.SIGTERM to group 165[0m
[[34m2025-09-20T06:31:28.921+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=165, status='terminated', exitcode=0, started='05:04:38') (165) terminated with exit code 0[0m
[[34m2025-09-20T06:31:28.975+0000[0m] {[34mmanager.py:[0m166} INFO[0m - Launched DagFileProcessorManager with pid: 1966[0m
[[34m2025-09-20T06:31:29.050+0000[0m] {[34msettings.py:[0m61} INFO[0m - Configured default timezone Timezone('UTC')[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-20T06:31:29.125+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T06:31:29.133+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py:407 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-20 06:47:58 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:1038)
[2025-09-20 06:47:58 +0000] [1038] [INFO] Worker exiting (pid: 1038)
[2025-09-20 06:47:58 +0000] [34] [ERROR] Worker (pid:1038) exited with code 1
[2025-09-20 06:47:58 +0000] [34] [ERROR] Worker (pid:1038) exited with code 1.
[2025-09-20 06:47:58 +0000] [2007] [INFO] Booting worker with pid: 2007
[[34m2025-09-20T06:47:59.557+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T06:47:59.597+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-20 07:00:39 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:1963)
[2025-09-20 07:00:39 +0000] [1963] [INFO] Worker exiting (pid: 1963)
[2025-09-20 07:00:39 +0000] [34] [ERROR] Worker (pid:1963) exited with code 1
[2025-09-20 07:00:39 +0000] [34] [ERROR] Worker (pid:1963) exited with code 1.
[2025-09-20 07:00:39 +0000] [2035] [INFO] Booting worker with pid: 2035
[[34m2025-09-20T07:00:40.185+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T07:00:40.193+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-20 07:11:58 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2007)
[2025-09-20 07:11:59 +0000] [2007] [INFO] Worker exiting (pid: 2007)
[2025-09-20 07:11:59 +0000] [34] [ERROR] Worker (pid:2007) exited with code 1
[2025-09-20 07:11:59 +0000] [34] [ERROR] Worker (pid:2007) exited with code 1.
[2025-09-20 07:11:59 +0000] [2090] [INFO] Booting worker with pid: 2090
[[34m2025-09-20T07:11:59.746+0000[0m] {[34mmanager.py:[0m302} ERROR[0m - DagFileProcessorManager (PID=1966) last sent a heartbeat 526.12 seconds ago! Restarting it[0m
[[34m2025-09-20T07:11:59.775+0000[0m] {[34mprocess_utils.py:[0m131} INFO[0m - Sending Signals.SIGTERM to group 1966. PIDs of all processes in the group: [2086, 1966][0m
[2025-09-20T07:11:59.853+0000] {processor.py:273} WARNING - Killing DAGFileProcessorProcess (PID=2086)
[[34m2025-09-20T07:11:59.824+0000[0m] {[34mprocess_utils.py:[0m86} INFO[0m - Sending the signal Signals.SIGTERM to group 1966[0m
[2025-09-20T07:12:01.102+0000] {process_utils.py:259} INFO - Waiting up to 5 seconds for processes to exit...
[[34m2025-09-20T07:12:01.111+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=2086, status='terminated', started='07:03:12') (2086) terminated with exit code None[0m
[[34m2025-09-20T07:12:01.122+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=1966, status='terminated', exitcode=0, started='06:31:28') (1966) terminated with exit code 0[0m
[[34m2025-09-20T07:12:01.128+0000[0m] {[34mmanager.py:[0m166} INFO[0m - Launched DagFileProcessorManager with pid: 2093[0m
[[34m2025-09-20T07:12:01.156+0000[0m] {[34msettings.py:[0m61} INFO[0m - Configured default timezone Timezone('UTC')[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-20T07:12:01.191+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T07:12:01.203+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py:407 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-20T07:22:43.359+0000[0m] {[34mmanager.py:[0m302} ERROR[0m - DagFileProcessorManager (PID=2093) last sent a heartbeat 594.54 seconds ago! Restarting it[0m
[[34m2025-09-20T07:22:43.365+0000[0m] {[34mprocess_utils.py:[0m131} INFO[0m - Sending Signals.SIGTERM to group 2093. PIDs of all processes in the group: [2093][0m
[[34m2025-09-20T07:22:43.369+0000[0m] {[34mprocess_utils.py:[0m86} INFO[0m - Sending the signal Signals.SIGTERM to group 2093[0m
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/handlers.py", line 69, in emit
    if self.shouldRollover(record):
  File "/usr/local/lib/python3.8/logging/handlers.py", line 186, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
RuntimeError: reentrant call inside <_io.BufferedWriter name='/opt/airflow/logs/dag_processor_manager/dag_processor_manager.log'>
Call stack:
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 57, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 85, in scheduler
    _run_scheduler_job(job_runner, skip_serve_logs=args.skip_serve_logs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 47, in _run_scheduler_job
    run_job(job=job_runner.job, execute_callable=job_runner._execute)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py", line 844, in _execute
    self._run_scheduler_loop()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/scheduler_job_runner.py", line 982, in _run_scheduler_loop
    self.processor_agent.heartbeat()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 273, in heartbeat
    self._heartbeat_manager()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 308, in _heartbeat_manager
    self.start()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 164, in start
    process.start()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 258, in _run_processor_manager
    processor_manager.start()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 493, in start
    return self._run_parsing_loop()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 621, in _run_parsing_loop
    refreshed_dag_dir = self._refresh_dag_dir()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 758, in _refresh_dag_dir
    self.log.info("There are %s files in %s", len(self._file_paths), self._dag_directory)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1446, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/local/lib/python3.8/logging/handlers.py", line 71, in emit
    logging.FileHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1187, in emit
    StreamHandler.emit(self, record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 469, in _exit_gracefully
    self.log.info("Exiting gracefully upon receiving signal %s", signum)
Message: 'Exiting gracefully upon receiving signal %s'
Arguments: (15,)
[[34m2025-09-20T07:22:44.946+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=2093, status='terminated', exitcode=0, started='07:11:59') (2093) terminated with exit code 0[0m
[[34m2025-09-20T07:22:44.952+0000[0m] {[34mmanager.py:[0m166} INFO[0m - Launched DagFileProcessorManager with pid: 2125[0m
[[34m2025-09-20T07:22:44.966+0000[0m] {[34msettings.py:[0m61} INFO[0m - Configured default timezone Timezone('UTC')[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-20T07:22:45.009+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T07:22:45.014+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py:407 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-20 07:39:34 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2090)
[2025-09-20 07:39:34 +0000] [2090] [INFO] Worker exiting (pid: 2090)
[2025-09-20 07:39:35 +0000] [34] [ERROR] Worker (pid:2090) exited with code 1
[2025-09-20 07:39:35 +0000] [34] [ERROR] Worker (pid:2090) exited with code 1.
[2025-09-20 07:39:35 +0000] [2152] [INFO] Booting worker with pid: 2152
[[34m2025-09-20T07:39:35.476+0000[0m] {[34mmanager.py:[0m302} ERROR[0m - DagFileProcessorManager (PID=2125) last sent a heartbeat 961.66 seconds ago! Restarting it[0m
[[34m2025-09-20T07:39:35.496+0000[0m] {[34mprocess_utils.py:[0m131} INFO[0m - Sending Signals.SIGTERM to group 2125. PIDs of all processes in the group: [2125][0m
[[34m2025-09-20T07:39:35.500+0000[0m] {[34mprocess_utils.py:[0m86} INFO[0m - Sending the signal Signals.SIGTERM to group 2125[0m
[[34m2025-09-20T07:39:37.064+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=2125, status='terminated', exitcode=0, started='07:22:45') (2125) terminated with exit code 0[0m
[[34m2025-09-20T07:39:37.070+0000[0m] {[34mmanager.py:[0m166} INFO[0m - Launched DagFileProcessorManager with pid: 2158[0m
[[34m2025-09-20T07:39:37.084+0000[0m] {[34msettings.py:[0m61} INFO[0m - Configured default timezone Timezone('UTC')[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-20T07:39:37.129+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T07:39:37.133+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py:407 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-20 07:50:01 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2035)
[2025-09-20 07:50:01 +0000] [2035] [INFO] Worker exiting (pid: 2035)
[2025-09-20 07:50:01 +0000] [34] [ERROR] Worker (pid:2035) exited with code 1
[2025-09-20 07:50:01 +0000] [34] [ERROR] Worker (pid:2035) exited with code 1.
[2025-09-20 07:50:01 +0000] [2173] [INFO] Booting worker with pid: 2173
[[34m2025-09-20T07:50:01.557+0000[0m] {[34mmanager.py:[0m302} ERROR[0m - DagFileProcessorManager (PID=2158) last sent a heartbeat 595.33 seconds ago! Restarting it[0m
[[34m2025-09-20T07:50:01.584+0000[0m] {[34mprocess_utils.py:[0m131} INFO[0m - Sending Signals.SIGTERM to group 2158. PIDs of all processes in the group: [2158][0m
[[34m2025-09-20T07:50:01.671+0000[0m] {[34mprocess_utils.py:[0m86} INFO[0m - Sending the signal Signals.SIGTERM to group 2158[0m
[[34m2025-09-20T07:50:03.309+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=2158, status='terminated', exitcode=0, started='07:39:35') (2158) terminated with exit code 0[0m
[[34m2025-09-20T07:50:03.315+0000[0m] {[34mmanager.py:[0m166} INFO[0m - Launched DagFileProcessorManager with pid: 2177[0m
[[34m2025-09-20T07:50:03.329+0000[0m] {[34msettings.py:[0m61} INFO[0m - Configured default timezone Timezone('UTC')[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-20T07:50:03.386+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T07:50:03.391+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py:407 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-20 08:00:39 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2152)
[2025-09-20 08:00:39 +0000] [2152] [INFO] Worker exiting (pid: 2152)
[2025-09-20 08:00:39 +0000] [34] [ERROR] Worker (pid:2152) exited with code 1
[2025-09-20 08:00:39 +0000] [34] [ERROR] Worker (pid:2152) exited with code 1.
[2025-09-20 08:00:39 +0000] [2200] [INFO] Booting worker with pid: 2200
[[34m2025-09-20T08:00:39.932+0000[0m] {[34mmanager.py:[0m302} ERROR[0m - DagFileProcessorManager (PID=2177) last sent a heartbeat 603.67 seconds ago! Restarting it[0m
[2025-09-20T08:00:40.009+0000] {processor.py:273} WARNING - Killing DAGFileProcessorProcess (PID=2192)
[[34m2025-09-20T08:00:40.011+0000[0m] {[34mprocess_utils.py:[0m131} INFO[0m - Sending Signals.SIGTERM to group 2177. PIDs of all processes in the group: [2192, 2195, 2177][0m
[[34m2025-09-20T08:00:40.022+0000[0m] {[34mprocess_utils.py:[0m86} INFO[0m - Sending the signal Signals.SIGTERM to group 2177[0m
[[34m2025-09-20T08:00:41.554+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=2192, status='terminated', started='07:50:35') (2192) terminated with exit code None[0m
[2025-09-20T08:00:42.314+0000] {process_utils.py:259} INFO - Waiting up to 5 seconds for processes to exit...
[[34m2025-09-20T08:00:42.368+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=2177, status='terminated', exitcode=0, started='07:50:04') (2177) terminated with exit code 0[0m
[[34m2025-09-20T08:00:42.370+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=2195, status='terminated', started='07:50:35') (2195) terminated with exit code None[0m
[[34m2025-09-20T08:00:42.376+0000[0m] {[34mmanager.py:[0m166} INFO[0m - Launched DagFileProcessorManager with pid: 2210[0m
[[34m2025-09-20T08:00:42.389+0000[0m] {[34msettings.py:[0m61} INFO[0m - Configured default timezone Timezone('UTC')[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py:407 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-20T08:00:42.462+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T08:00:42.471+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-20 08:12:38 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2173)
[2025-09-20 08:12:37 +0000] [2173] [INFO] Worker exiting (pid: 2173)
[2025-09-20 08:12:37 +0000] [34] [ERROR] Worker (pid:2173) exited with code 1
[2025-09-20 08:12:37 +0000] [34] [ERROR] Worker (pid:2173) exited with code 1.
[2025-09-20 08:12:37 +0000] [2225] [INFO] Booting worker with pid: 2225
[[34m2025-09-20T08:12:37.780+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T08:12:37.806+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-20T08:23:34.456+0000] {processor.py:273} WARNING - Killing DAGFileProcessorProcess (PID=2238)
[2025-09-20T08:23:34.551+0000] {processor.py:273} WARNING - Killing DAGFileProcessorProcess (PID=2241)
[[34m2025-09-20T08:23:34.848+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T08:23:34.856+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-20 08:34:22 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2200)
[2025-09-20 08:34:22 +0000] [2200] [INFO] Worker exiting (pid: 2200)
[2025-09-20 08:34:22 +0000] [34] [ERROR] Worker (pid:2200) exited with code 1
[2025-09-20 08:34:22 +0000] [34] [ERROR] Worker (pid:2200) exited with code 1.
[2025-09-20 08:34:22 +0000] [2257] [INFO] Booting worker with pid: 2257
[[34m2025-09-20T08:34:22.827+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T08:34:22.853+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[[34m2025-09-20T08:43:13.858+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T08:43:13.951+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-20 09:17:28 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2225)
[2025-09-20 09:17:28 +0000] [2225] [INFO] Worker exiting (pid: 2225)
[2025-09-20 09:17:29 +0000] [34] [ERROR] Worker (pid:2225) exited with code 1
[2025-09-20 09:17:29 +0000] [34] [ERROR] Worker (pid:2225) exited with code 1.
[2025-09-20 09:17:29 +0000] [2306] [INFO] Booting worker with pid: 2306
[[34m2025-09-20T09:17:29.457+0000[0m] {[34mmanager.py:[0m302} ERROR[0m - DagFileProcessorManager (PID=2210) last sent a heartbeat 2016.66 seconds ago! Restarting it[0m
[[34m2025-09-20T09:17:29.473+0000[0m] {[34mprocess_utils.py:[0m131} INFO[0m - Sending Signals.SIGTERM to group 2210. PIDs of all processes in the group: [2210][0m
[[34m2025-09-20T09:17:29.661+0000[0m] {[34mprocess_utils.py:[0m86} INFO[0m - Sending the signal Signals.SIGTERM to group 2210[0m
[[34m2025-09-20T09:17:30.634+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=2210, status='terminated', exitcode=0, started='08:00:41') (2210) terminated with exit code 0[0m
[[34m2025-09-20T09:17:30.642+0000[0m] {[34mmanager.py:[0m166} INFO[0m - Launched DagFileProcessorManager with pid: 2309[0m
[[34m2025-09-20T09:17:30.668+0000[0m] {[34msettings.py:[0m61} INFO[0m - Configured default timezone Timezone('UTC')[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-20T09:17:30.714+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T09:17:30.723+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py:407 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-20 09:24:09 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2257)
[2025-09-20 09:24:09 +0000] [2257] [INFO] Worker exiting (pid: 2257)
[2025-09-20 09:24:09 +0000] [34] [ERROR] Worker (pid:2257) exited with code 1
[2025-09-20 09:24:09 +0000] [34] [ERROR] Worker (pid:2257) exited with code 1.
[2025-09-20 09:24:09 +0000] [2324] [INFO] Booting worker with pid: 2324
[[34m2025-09-20T09:24:09.227+0000[0m] {[34mmanager.py:[0m302} ERROR[0m - DagFileProcessorManager (PID=2309) last sent a heartbeat 372.08 seconds ago! Restarting it[0m
[[34m2025-09-20T09:24:09.231+0000[0m] {[34mprocess_utils.py:[0m131} INFO[0m - Sending Signals.SIGTERM to group 2309. PIDs of all processes in the group: [2309][0m
[[34m2025-09-20T09:24:09.233+0000[0m] {[34mprocess_utils.py:[0m86} INFO[0m - Sending the signal Signals.SIGTERM to group 2309[0m
[2025-09-20T09:24:11.273+0000] {process_utils.py:259} INFO - Waiting up to 5 seconds for processes to exit...
[[34m2025-09-20T09:24:11.308+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=2309, status='terminated', exitcode=0, started='09:17:32') (2309) terminated with exit code 0[0m
[[34m2025-09-20T09:24:11.314+0000[0m] {[34mmanager.py:[0m166} INFO[0m - Launched DagFileProcessorManager with pid: 2329[0m
[[34m2025-09-20T09:24:11.329+0000[0m] {[34msettings.py:[0m61} INFO[0m - Configured default timezone Timezone('UTC')[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py:407 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-20T09:24:11.550+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-20T09:24:11.558+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-20 09:58:23 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2306)
[2025-09-20 09:58:23 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2324)
[2025-09-20 09:58:23 +0000] [2306] [INFO] Worker exiting (pid: 2306)
[2025-09-20 09:58:23 +0000] [2324] [INFO] Worker exiting (pid: 2324)
[2025-09-20 09:58:23 +0000] [34] [ERROR] Worker (pid:2306) exited with code 1
[2025-09-20 09:58:23 +0000] [34] [ERROR] Worker (pid:2306) exited with code 1.
[2025-09-20 09:58:23 +0000] [34] [ERROR] Worker (pid:2324) exited with code 1
[2025-09-20 09:58:23 +0000] [34] [ERROR] Worker (pid:2324) exited with code 1.
[2025-09-20 09:58:24 +0000] [2392] [INFO] Booting worker with pid: 2392
[2025-09-20 09:58:24 +0000] [2393] [INFO] Booting worker with pid: 2393
[2025-09-20 10:10:14 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2392)
[2025-09-20 10:10:14 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2393)
[2025-09-20 10:10:14 +0000] [2393] [INFO] Worker exiting (pid: 2393)
[2025-09-20 10:10:14 +0000] [2392] [INFO] Worker exiting (pid: 2392)
[2025-09-20 10:10:14 +0000] [34] [ERROR] Worker (pid:2392) exited with code 1
[2025-09-20 10:10:14 +0000] [34] [ERROR] Worker (pid:2392) exited with code 1.
[2025-09-20 10:10:14 +0000] [34] [ERROR] Worker (pid:2393) exited with code 1
[2025-09-20 10:10:14 +0000] [34] [ERROR] Worker (pid:2393) exited with code 1.
[2025-09-20 10:10:15 +0000] [2422] [INFO] Booting worker with pid: 2422
[2025-09-20 10:10:15 +0000] [2423] [INFO] Booting worker with pid: 2423
[[34m2025-09-20T10:11:11.094+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[2025-09-20 17:30:52 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2422)
[2025-09-20 17:30:52 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2423)
[2025-09-20 17:30:52 +0000] [2422] [INFO] Worker exiting (pid: 2422)
[2025-09-20 17:30:52 +0000] [2423] [INFO] Worker exiting (pid: 2423)
[2025-09-20 17:30:52 +0000] [34] [ERROR] Worker (pid:2422) exited with code 1
[2025-09-20 17:30:52 +0000] [34] [ERROR] Worker (pid:2422) exited with code 1.
[2025-09-20 17:30:52 +0000] [34] [ERROR] Worker (pid:2423) exited with code 1
[2025-09-20 17:30:52 +0000] [34] [ERROR] Worker (pid:2423) exited with code 1.
[2025-09-20 17:30:52 +0000] [2452] [INFO] Booting worker with pid: 2452
[2025-09-20 17:30:52 +0000] [2453] [INFO] Booting worker with pid: 2453
[2025-09-20 17:51:55 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2452)
[2025-09-20 17:52:02 +0000] [2452] [INFO] Worker exiting (pid: 2452)
[2025-09-20 17:52:04 +0000] [34] [ERROR] Worker (pid:2452) exited with code 1
[2025-09-20 17:52:04 +0000] [34] [ERROR] Worker (pid:2452) exited with code 1.
[2025-09-20 17:52:04 +0000] [2483] [INFO] Booting worker with pid: 2483
[2025-09-20 18:13:03 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2453)
[2025-09-20 18:13:03 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2483)
[2025-09-20 18:13:03 +0000] [2453] [INFO] Worker exiting (pid: 2453)
[2025-09-20 18:13:03 +0000] [2483] [INFO] Worker exiting (pid: 2483)
[2025-09-20 18:13:04 +0000] [34] [ERROR] Worker (pid:2483) exited with code 1
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
Call stack:
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 57, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 85, in scheduler
    _run_scheduler_job(job_runner, skip_serve_logs=args.skip_serve_logs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 45, in _run_scheduler_job
    with _serve_logs(skip_serve_logs), _serve_health_check(enable_health_check):
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 98, in _serve_logs
    sub_proc.start()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/serve_logs.py", line 179, in serve_logs
    StandaloneGunicornApplication(wsgi_app, options).run()
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 360, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 527, in reap_workers
    self.log.error('Worker (pid:%s) exited with code %s', wpid, exitcode)
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/glogging.py", line 272, in error
    self.error_log.error(msg, *args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 538, in reap_workers
    self.log.error("Worker (pid:%s) exited with code %s.",
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/glogging.py", line 272, in error
    self.error_log.error(msg, *args, **kwargs)
Message: 'Worker (pid:%s) exited with code %s.'
Arguments: (2453, 1)
[2025-09-20 18:13:05 +0000] [34] [ERROR] Worker (pid:2483) exited with code 1.
[2025-09-20 18:13:05 +0000] [2516] [INFO] Booting worker with pid: 2516
[2025-09-20 18:13:05 +0000] [2518] [INFO] Booting worker with pid: 2518
[2025-09-20 18:13:50 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2516)
[2025-09-20 18:13:50 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2518)
[2025-09-20 18:13:50 +0000] [2518] [INFO] Worker exiting (pid: 2518)
[2025-09-20 18:13:50 +0000] [2516] [INFO] Worker exiting (pid: 2516)
[2025-09-20 18:13:50 +0000] [34] [ERROR] Worker (pid:2518) exited with code 1
[2025-09-20 18:13:50 +0000] [34] [ERROR] Worker (pid:2518) exited with code 1.
[2025-09-20 18:13:50 +0000] [34] [ERROR] Worker (pid:2516) exited with code 1
[2025-09-20 18:13:50 +0000] [34] [ERROR] Worker (pid:2516) exited with code 1.
[2025-09-20 18:13:50 +0000] [2533] [INFO] Booting worker with pid: 2533
[2025-09-20 18:13:51 +0000] [2534] [INFO] Booting worker with pid: 2534
[2025-09-21 06:26:06 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2533)
[2025-09-21 06:26:06 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2534)
[2025-09-21 06:26:06 +0000] [2534] [INFO] Worker exiting (pid: 2534)
[2025-09-21 06:26:06 +0000] [2533] [INFO] Worker exiting (pid: 2533)
[2025-09-21 06:26:06 +0000] [34] [ERROR] Worker (pid:2534) exited with code 1
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
Call stack:
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 57, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 85, in scheduler
    _run_scheduler_job(job_runner, skip_serve_logs=args.skip_serve_logs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 45, in _run_scheduler_job
    with _serve_logs(skip_serve_logs), _serve_health_check(enable_health_check):
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/scheduler_command.py", line 98, in _serve_logs
    sub_proc.start()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.8/multiprocessing/popen_fork.py", line 75, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/serve_logs.py", line 179, in serve_logs
    StandaloneGunicornApplication(wsgi_app, options).run()
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 360, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 527, in reap_workers
    self.log.error('Worker (pid:%s) exited with code %s', wpid, exitcode)
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/glogging.py", line 272, in error
    self.error_log.error(msg, *args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1089, in emit
    self.flush()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1069, in flush
    self.stream.flush()
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/arbiter.py", line 538, in reap_workers
    self.log.error("Worker (pid:%s) exited with code %s.",
  File "/home/airflow/.local/lib/python3.8/site-packages/gunicorn/glogging.py", line 272, in error
    self.error_log.error(msg, *args, **kwargs)
Message: 'Worker (pid:%s) exited with code %s.'
Arguments: (2533, 1)
[2025-09-21 06:26:06 +0000] [34] [ERROR] Worker (pid:2534) exited with code 1.
[2025-09-21 06:26:06 +0000] [2574] [INFO] Booting worker with pid: 2574
[2025-09-21 06:26:07 +0000] [2579] [INFO] Booting worker with pid: 2579
[2025-09-21 07:04:59 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2579)
[2025-09-21 07:04:59 +0000] [2579] [INFO] Worker exiting (pid: 2579)
[2025-09-21 07:05:01 +0000] [34] [ERROR] Worker (pid:2579) exited with code 1
[2025-09-21 07:05:01 +0000] [34] [ERROR] Worker (pid:2579) exited with code 1.
[2025-09-21 07:05:02 +0000] [2589] [INFO] Booting worker with pid: 2589
[[34m2025-09-21T07:05:14.571+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-21T07:10:18.835+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-21T07:15:18.909+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-21T07:20:18.986+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-21T07:25:19.137+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[2025-09-21 07:33:06 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2574)
[2025-09-21 07:33:07 +0000] [2574] [INFO] Worker exiting (pid: 2574)
[2025-09-21 07:33:06 +0000] [34] [ERROR] Worker (pid:2574) exited with code 1
[2025-09-21 07:33:06 +0000] [34] [ERROR] Worker (pid:2574) exited with code 1.
[2025-09-21 07:33:10 +0000] [3060] [INFO] Booting worker with pid: 3060
[[34m2025-09-21T07:33:13.205+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-21T07:33:13.518+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-22 00:20:52 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:2589)
[2025-09-22 00:21:00 +0000] [34] [ERROR] Worker (pid:2589) was sent SIGKILL! Perhaps out of memory?
[2025-09-22 00:21:00 +0000] [3078] [INFO] Booting worker with pid: 3078
[2025-09-22 00:26:30 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:3078)
[2025-09-22 00:26:30 +0000] [3078] [INFO] Worker exiting (pid: 3078)
[2025-09-22 00:26:31 +0000] [34] [ERROR] Worker (pid:3078) exited with code 1
[2025-09-22 00:26:31 +0000] [34] [ERROR] Worker (pid:3078) exited with code 1.
[2025-09-22 00:26:31 +0000] [3154] [INFO] Booting worker with pid: 3154
[[34m2025-09-22T00:26:31.829+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T00:26:32.014+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-22 00:39:09 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:3060)
[2025-09-22 00:39:10 +0000] [3060] [INFO] Worker exiting (pid: 3060)
[2025-09-22 00:39:10 +0000] [34] [ERROR] Worker (pid:3060) exited with code 1
[2025-09-22 00:39:10 +0000] [34] [ERROR] Worker (pid:3060) exited with code 1.
[2025-09-22 00:39:10 +0000] [3217] [INFO] Booting worker with pid: 3217
[[34m2025-09-22T00:39:11.159+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T00:39:11.164+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[[34m2025-09-22T00:47:16.271+0000[0m] {[34mmanager.py:[0m302} ERROR[0m - DagFileProcessorManager (PID=2329) last sent a heartbeat 332.89 seconds ago! Restarting it[0m
[[34m2025-09-22T00:47:16.374+0000[0m] {[34mprocess_utils.py:[0m131} INFO[0m - Sending Signals.SIGTERM to group 2329. PIDs of all processes in the group: [3279, 2329][0m
[[34m2025-09-22T00:47:16.375+0000[0m] {[34mprocess_utils.py:[0m86} INFO[0m - Sending the signal Signals.SIGTERM to group 2329[0m
[2025-09-22T00:47:18.309+0000] {process_utils.py:259} INFO - Waiting up to 5 seconds for processes to exit...
Exception ignored in: <function _releaseLock at 0x7f6d3da1eee0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/__init__.py", line 227, in _releaseLock
    def _releaseLock():
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 474, in _exit_gracefully
    sys.exit(os.EX_OK)
SystemExit: 0
[[34m2025-09-22T00:47:18.474+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=3279, status='terminated', started='2025-09-20 10:29:12') (3279) terminated with exit code None[0m
Process ForkProcess-43:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 258, in _run_processor_manager
    processor_manager.start()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 493, in start
    return self._run_parsing_loop()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 650, in _run_parsing_loop
    self.collect_results()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 1055, in collect_results
    self._collect_results_from_processor(processor)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py", line 1022, in _collect_results_from_processor
    if processor.result is not None:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 349, in result
    if not self.done:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/processor.py", line 317, in done
    if self._parent_channel.poll():
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 255, in poll
    self._check_closed()
  File "/usr/local/lib/python3.8/multiprocessing/connection.py", line 136, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
[[34m2025-09-22T00:47:18.858+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=2329, status='terminated', exitcode=1, started='2025-09-20 09:24:14') (2329) terminated with exit code 1[0m
[[34m2025-09-22T00:47:18.866+0000[0m] {[34mmanager.py:[0m166} INFO[0m - Launched DagFileProcessorManager with pid: 3290[0m
[[34m2025-09-22T00:47:18.897+0000[0m] {[34msettings.py:[0m61} INFO[0m - Configured default timezone Timezone('UTC')[0m
[[34m2025-09-22T00:47:18.920+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-22T00:47:18.925+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py:407 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-22 00:59:14 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:3154)
[2025-09-22 00:59:14 +0000] [3154] [INFO] Worker exiting (pid: 3154)
[2025-09-22 00:59:15 +0000] [34] [ERROR] Worker (pid:3154) exited with code 1
[2025-09-22 00:59:15 +0000] [34] [ERROR] Worker (pid:3154) exited with code 1.
[2025-09-22 00:59:16 +0000] [3329] [INFO] Booting worker with pid: 3329
[[34m2025-09-22T00:59:16.350+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T00:59:16.357+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-22 01:05:55 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:3329)
[2025-09-22 01:05:55 +0000] [3329] [INFO] Worker exiting (pid: 3329)
[2025-09-22 01:05:55 +0000] [34] [ERROR] Worker (pid:3329) exited with code 1
[2025-09-22 01:05:55 +0000] [34] [ERROR] Worker (pid:3329) exited with code 1.
[2025-09-22 01:05:55 +0000] [3405] [INFO] Booting worker with pid: 3405
[[34m2025-09-22T01:05:55.927+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T01:05:55.949+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-22 01:23:02 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:3217)
[2025-09-22 01:23:02 +0000] [3217] [INFO] Worker exiting (pid: 3217)
[2025-09-22 01:23:03 +0000] [34] [ERROR] Worker (pid:3217) exited with code 1
[2025-09-22 01:23:03 +0000] [34] [ERROR] Worker (pid:3217) exited with code 1.
[2025-09-22 01:23:03 +0000] [3457] [INFO] Booting worker with pid: 3457
[[34m2025-09-22T01:23:04.129+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T01:23:04.197+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-22 01:24:33 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:3405)
[2025-09-22 01:24:33 +0000] [3405] [INFO] Worker exiting (pid: 3405)
[2025-09-22 01:24:33 +0000] [34] [ERROR] Worker (pid:3405) exited with code 1
[2025-09-22 01:24:33 +0000] [34] [ERROR] Worker (pid:3405) exited with code 1.
[2025-09-22 01:24:33 +0000] [3497] [INFO] Booting worker with pid: 3497
[[34m2025-09-22T01:28:22.859+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T01:33:22.949+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T01:38:23.081+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T01:43:23.220+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[2025-09-22 02:06:31 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:3457)
[2025-09-22 02:06:31 +0000] [3457] [INFO] Worker exiting (pid: 3457)
[2025-09-22 02:06:30 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:3497)
[2025-09-22 02:06:30 +0000] [34] [ERROR] Worker (pid:3457) exited with code 1
[2025-09-22 02:06:30 +0000] [34] [ERROR] Worker (pid:3457) exited with code 1.
[2025-09-22 02:06:30 +0000] [4008] [INFO] Booting worker with pid: 4008
[2025-09-22 02:06:30 +0000] [3497] [INFO] Worker exiting (pid: 3497)
[2025-09-22 02:06:32 +0000] [34] [ERROR] Worker (pid:3497) was sent SIGKILL! Perhaps out of memory?
[2025-09-22 02:06:32 +0000] [4013] [INFO] Booting worker with pid: 4013
[[34m2025-09-22T02:06:32.529+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T02:06:32.535+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[[34m2025-09-22T02:11:32.990+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T02:16:33.068+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T02:21:33.145+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T02:26:33.211+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[2025-09-22 02:31:49 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:4008)
[2025-09-22 02:31:49 +0000] [4008] [INFO] Worker exiting (pid: 4008)
[2025-09-22 02:31:49 +0000] [34] [ERROR] Worker (pid:4008) exited with code 1
[2025-09-22 02:31:49 +0000] [34] [ERROR] Worker (pid:4008) exited with code 1.
[2025-09-22 02:31:49 +0000] [4555] [INFO] Booting worker with pid: 4555
[[34m2025-09-22T02:31:50.887+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T02:31:50.893+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[[34m2025-09-22T02:36:51.751+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T02:41:51.782+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T02:46:52.133+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T02:51:52.208+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T02:56:52.293+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T03:01:52.376+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T03:06:52.450+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T03:11:52.542+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T03:20:11.526+0000[0m] {[34mmanager.py:[0m302} ERROR[0m - DagFileProcessorManager (PID=3290) last sent a heartbeat 404.38 seconds ago! Restarting it[0m
[[34m2025-09-22T03:20:11.710+0000[0m] {[34mprocess_utils.py:[0m131} INFO[0m - Sending Signals.SIGTERM to group 3290. PIDs of all processes in the group: [3290][0m
[[34m2025-09-22T03:20:11.756+0000[0m] {[34mprocess_utils.py:[0m86} INFO[0m - Sending the signal Signals.SIGTERM to group 3290[0m
[[34m2025-09-22T03:20:14.512+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=3290, status='terminated', exitcode=0, started='2025-09-20 10:29:15') (3290) terminated with exit code 0[0m
[[34m2025-09-22T03:20:14.526+0000[0m] {[34mmanager.py:[0m166} INFO[0m - Launched DagFileProcessorManager with pid: 5497[0m
[[34m2025-09-22T03:20:14.611+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T03:20:14.576+0000[0m] {[34msettings.py:[0m61} INFO[0m - Configured default timezone Timezone('UTC')[0m
[[34m2025-09-22T03:20:14.675+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py:407 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-09-22 03:29:13 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:4013)
[2025-09-22 03:29:14 +0000] [4013] [INFO] Worker exiting (pid: 4013)
[2025-09-22 03:29:14 +0000] [34] [ERROR] Worker (pid:4013) exited with code 1
[2025-09-22 03:29:14 +0000] [34] [ERROR] Worker (pid:4013) exited with code 1.
[2025-09-22 03:29:14 +0000] [5515] [INFO] Booting worker with pid: 5515
[[34m2025-09-22T03:29:15.052+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T03:29:15.128+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-22 03:34:40 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:4555)
[2025-09-22 03:34:41 +0000] [4555] [INFO] Worker exiting (pid: 4555)
[2025-09-22 03:34:40 +0000] [34] [ERROR] Worker (pid:4555) exited with code 1
[2025-09-22 03:34:40 +0000] [34] [ERROR] Worker (pid:4555) exited with code 1.
[2025-09-22 03:34:40 +0000] [5527] [INFO] Booting worker with pid: 5527
[[34m2025-09-22T03:34:41.470+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T03:34:41.547+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[[34m2025-09-22T03:39:42.799+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[2025-09-22 03:52:56 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:5515)
[2025-09-22 03:52:56 +0000] [5515] [INFO] Worker exiting (pid: 5515)
[2025-09-22 03:52:57 +0000] [34] [ERROR] Worker (pid:5515) exited with code 1
[2025-09-22 03:52:57 +0000] [34] [ERROR] Worker (pid:5515) exited with code 1.
[2025-09-22 03:52:57 +0000] [5676] [INFO] Booting worker with pid: 5676
[[34m2025-09-22T03:52:57.899+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T03:52:57.973+0000[0m] {[34mscheduler_job_runner.py:[0m1628} INFO[0m - Marked 1 SchedulerJob instances as failed[0m
[2025-09-22 03:54:37 +0000] [34] [CRITICAL] WORKER TIMEOUT (pid:5527)
[2025-09-22 03:54:37 +0000] [5527] [INFO] Worker exiting (pid: 5527)
[2025-09-22 03:54:37 +0000] [34] [ERROR] Worker (pid:5527) exited with code 1
[2025-09-22 03:54:36 +0000] [34] [ERROR] Worker (pid:5527) exited with code 1.
[[34m2025-09-22T03:54:36.144+0000[0m] {[34mmanager.py:[0m302} ERROR[0m - DagFileProcessorManager (PID=5497) last sent a heartbeat 95.37 seconds ago! Restarting it[0m
[[34m2025-09-22T03:54:36.388+0000[0m] {[34mprocess_utils.py:[0m131} INFO[0m - Sending Signals.SIGTERM to group 5497. PIDs of all processes in the group: [5690, 5693, 5497][0m
[[34m2025-09-22T03:54:36.396+0000[0m] {[34mprocess_utils.py:[0m86} INFO[0m - Sending the signal Signals.SIGTERM to group 5497[0m
[2025-09-22 03:54:36 +0000] [5696] [INFO] Booting worker with pid: 5696
[2025-09-22T03:54:39.821+0000] {process_utils.py:259} INFO - Waiting up to 5 seconds for processes to exit...
[2025-09-22T03:54:39.840+0000] {process_utils.py:259} INFO - Waiting up to 5 seconds for processes to exit...
[[34m2025-09-22T03:54:39.865+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=5497, status='terminated', exitcode=0, started='2025-09-20 13:02:08') (5497) terminated with exit code 0[0m
[[34m2025-09-22T03:54:39.866+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=5690, status='terminated', started='2025-09-20 13:36:30') (5690) terminated with exit code None[0m
[[34m2025-09-22T03:54:39.867+0000[0m] {[34mprocess_utils.py:[0m79} INFO[0m - Process psutil.Process(pid=5693, status='terminated', started='2025-09-20 13:36:30') (5693) terminated with exit code None[0m
[[34m2025-09-22T03:54:39.874+0000[0m] {[34mmanager.py:[0m166} INFO[0m - Launched DagFileProcessorManager with pid: 5703[0m
[[34m2025-09-22T03:54:39.929+0000[0m] {[34msettings.py:[0m61} INFO[0m - Configured default timezone Timezone('UTC')[0m
/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
/home/airflow/.local/lib/python3.8/site-packages/airflow/dag_processing/manager.py:407 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[[34m2025-09-22T03:57:57.896+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T04:02:57.932+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T04:07:57.968+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T04:12:58.152+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T04:17:58.239+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T04:22:58.331+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T04:27:58.443+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T04:32:58.538+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T04:37:58.649+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T04:42:58.737+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T04:47:58.829+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T04:52:58.915+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T04:57:58.994+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T05:02:59.081+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T05:07:59.181+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T05:12:59.297+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T05:17:59.387+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T05:22:59.478+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T05:27:59.570+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
[[34m2025-09-22T05:32:59.655+0000[0m] {[34mscheduler_job_runner.py:[0m1605} INFO[0m - Adopting or resetting orphaned tasks for active dag runs[0m
